elekarz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('django.contrib.auth.urls')),
]

main/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),

    path('new/<mode>/', views.newRegister, name='new'),

    path('register/<mode>', views.registerUser, name='register'),
    path('doctorRegister/', views.registerDoctor, name='registerDoctor'),

    path('activate_user/<uidb64>/<token>', views.activate_user, name='activate_user'),
    path('activate_doctor/<uidb64>/<token>', views.activate_doctor, name='activate_doctor'),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('delete/', views.deleteuser, name='delete'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name="password_change"),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),


    path('edit/', views.editProfile, name='editProfile'),
    path('editDoc/', views.editDocProfile, name='editDocProfile'),
    path('profile/', views.profileView, name='profileView'),

    path('doctor/<int:id>/', views.docProfile, name='docProfile'),
    #path('search', views.search, name='search'),
    re_path(r'^search/$', views.search, name='search'),

    path('appointment/<int:id>', views.makeAppointment, name='appointment'),
]

main/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import AbstractUser
from django.forms import ChoiceField
from datetime import time

class CustomUser(AbstractUser):
    #AbstractUser already holds first- and lastname, as well as email
    second_name = models.CharField(max_length=50, blank=True, null=True, verbose_name="Drugie imię")
    PESEL = models.IntegerField(unique=True, validators=[MinValueValidator(90000000000),MaxValueValidator(99999999999)])
    city = models.CharField(max_length=50, verbose_name="Miasto")
    address = models.CharField(max_length=255, verbose_name="Adres zamieszkania")
    phone_number = models.IntegerField(verbose_name="Numer telefonu", unique=True, validators=[MinValueValidator(100000000),MaxValueValidator(999999999)])
    isDoctor = models.BooleanField(default=False)

class DoctorProfile(models.Model):

    SPECS = [
        ("kardiolog", "Kardiolog"), ("kardiochirurg", "Kardiochirurg"),
        ("ortopeda", "Ortopeda"), ("fizjoterapeuta", "Fizjoterapeuta"),
        ("psycholog", "Psycholog"),  ("psychoterapeuta", "Psychoterapeuta"),
        ("psychiatra", "Psychiatra"),  ("psychiatra_dziecięcy", "Psychiatra dziecięcy"),
        ("weterynarz", "Weterynarz"),  ("pediatra", "Pediatra"),
        ("hepatolog", "Hepatolog"),  ("nefrolog", "Nefrolog"),
        ("stomatolog", "Stomatolog"),  ("dermatolog", "Dermatolog"),
        ("neurolog", "Neurolog"),  ("neurochirurg", "Neurochirurg"),
        ("chirurg", "Chirurg"),  ("kardiochirurg", "Kardiochirurg"),
        ("hematolog", "Hematolog"),  ("laryngolog", "Laryngolog"),
        ("alergolog", "Alergolog"),  ("pulmunolog", "Pulmunolog"),
        ("anestezjolog", "Anestezjolog"),  ("lekarz_rodzinny", "Lekarz rodzinny"),
        ("lekarz_medycyny_pracy", "Lekarz medycyny pracy"),  ("gastrolog", "Gastrolog"),
        ("ginekolog", "Ginekolog"),  ("endokrynolog", "Endokrynolog"),
    ]

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='doctor_profile', primary_key=True)
    description = models.TextField(verbose_name="Opis")
    PWZ_number = models.IntegerField(blank=True, null=True, verbose_name="Numer licencji lekarskiej", unique=True, validators=[MinValueValidator(100000),MaxValueValidator(999999)])
    facility = models.CharField(max_length=255, verbose_name="Placówka")
    city = models.CharField(max_length=50, verbose_name="Miasto")
    address = models.CharField(max_length=255, verbose_name="Adres") 
    spec1 = models.CharField(max_length=50, choices=(SPECS), verbose_name="Główna specjalizacja") #choice
    spec2 = models.CharField(max_length=50, choices=(SPECS), blank=True, null=True, verbose_name="Dodatkowa specjalizacja (opcjonalna)") #choice

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('main:docProfile', kwargs={'id':self.user.id})

class Appointment(models.Model):

    HOURS = [
        (time(8, 00), "8:00"), (time(8, 30), "8:30"),
        (time(9, 00), "9:00"), (time(9, 30), "9:30"),
        (time(10, 00), "10:00"), (time(10, 30), "10:30"),
        (time(11, 00), "11:00"), (time(11, 30), "11:30"),
        (time(12, 00), "12:00"), (time(12, 30), "12:30"),
        (time(13, 00), "13:00"), (time(13, 30), "13:30"),
        (time(14, 00), "14:00"), (time(14, 30), "14:30"),
        (time(15, 00), "15:00"), (time(15, 30), "15:30"),
        (time(16, 00), "16:00"), (time(16, 30), "16:30"),
        (time(17, 00), "17:00"), (time(17, 30), "17:30"),
        (time(18, 00), "18:00"), (time(18, 30), "18:30"),
        (time(19, 00), "19:00"), (time(19, 30), "19:30"),
        (time(20, 00), "20:00"), (time(20, 30), "20:30")        
    ]

    patient = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="patient", null=True, blank=True)
    doctor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="doc")
    
    first_name = models.CharField(max_length=30, verbose_name="Imię", null=True, blank=True)
    last_name = models.CharField(max_length=50, verbose_name="Nazwisko", null=True, blank=True)
    phone_number = models.IntegerField(verbose_name="Numer telefonu", null=True, blank=True)
    
    date = models.DateField(verbose_name="Dzień wizyty")
    hour = models.TimeField(choices=HOURS, verbose_name="Godzina wizyty")
    cause = models.TextField(verbose_name="Powód wizyty")

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="author")
    doctor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="commented_doc")

    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.CharField(max_length=1000, verbose_name="Treść komentarza:")

    def __str__(self) -> str:
        return f"{self.author} (id={self.author.id}) commented on {self.doctor} (id={self.doctor.id})"

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .tokens import account_activation_token
from django.template.loader import render_to_string
from django.core.mail import EmailMessage


from .models import Appointment, DoctorProfile, Comment, CustomUser
from .forms import UserRegistrationForm, DoctorProfileForm, CommentForm, UserEditForm, AppointmentFormAnonymous, AppointmentFormLogged, NewForm, UserDeleteForm
from .filters import DocFilterBySpec, DocFilterByCity
from datetime import datetime

def newRegister(request, mode='user'):
    if request.method == 'POST':
        form = NewForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False, mode=mode)
            user.is_active = False
            user.save(mode)
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            if mode!="doctor":
                message = render_to_string('registration/userConfirmation.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })

            else:
                message = render_to_string('registration/doctorConfirmation.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            

            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return render(request, 'registration/waitForActivate.html')
    else:
        form = NewForm()
    return render(request, 'registration/new.html', {'user_form': form, 'mode1':mode})


def oldRegister(request, mode='user'):
    if request.method == "POST":
        form = NewForm(request.POST)
        if form.is_valid():
            user = form.save(mode)
            login(request, user)
            messages.success(request, "Pomyślnie zarejestrowano konto." )
            if mode != "doctor":
                return redirect("main:home")
            else:
                return redirect("main:registerDoctor")
        messages.error(request, "Nie wszystkie pola zostały poprawnie uzupełnione.")
    else:
        form = NewForm()
    context = {"user_form":form, 'mode1':mode}
    return render(request, 'registration/new.html', context)

def activate_user(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(request, "Pomyślnie aktywowano konto." )
        return redirect('main:home')
    else:
        return render(request, 'registration/invalidActivation.html')

def activate_doctor(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect("main:registerDoctor")
    else:
        return render(request, 'registration/invalidActivation.html')

@login_required
def logout_request(request):
    logout(request)
    messages.info(request, "Wylogowano z konta.") 
    return redirect("main:home")

def registerUser(request, mode):
    if request.method == "POST":
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save(mode)
            new_user = authenticate(username=user_form.cleaned_data['username'],
                                    password=user_form.cleaned_data['password'],
                                    )
            login(request, new_user)
            if mode != "doctor":
                return HttpResponseRedirect("/")
            else:
                return HttpResponseRedirect("/doctorRegister/")
    else:
        user_form = UserRegistrationForm()
    context = {'user_form':user_form, 'mode': mode}
    return render(request, 'registration/userRegister.html', context)

def registerDoctor(request):
    #request.user.id
    if request.method == "POST":
        doc = DoctorProfile.objects.create(user=request.user)
        doctor_profile_form = DoctorProfileForm(instance=doc, data=request.POST)
        if doctor_profile_form.is_valid():
            doctor_profile_form.save()
            return redirect("main:home")
    else:
        doctor_profile_form = DoctorProfileForm()
    context = {'doc_form': doctor_profile_form}
    return render(request, 'registration/doctorRegister.html', context)

def home(request):
    docs = DoctorProfile.objects.all()
    doc_filter = DocFilterBySpec(request.GET, queryset=docs)
    #city_filter = DocFilterByCity(request.GET, queryset=docs)
    context = {'docList':doc_filter}
    return render(request, 'homepage/home.html', context)

def docProfile(request, id):
    doc = get_object_or_404(DoctorProfile, user=id)
    comments = Comment.objects.filter(doctor=doc.user)
    #print(f"Doc id is {id}")

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.instance.author = request.user
            form.instance.doctor = doc.user
            form.save()
    else:
        form = CommentForm()

    context = {'doc': doc, 'comments': comments, 'comment_form':form}
    return render(request, 'docProfile/docProfile.html', context)

def search(request):
    docs = DoctorProfile.objects.all()
    doc_filter = DocFilterBySpec(request.GET, queryset=docs)
    city_filter = DocFilterByCity(request.GET, queryset=docs)
    context = {'docList':doc_filter, 'cityFilter':city_filter}
    return render(request, 'search.html', context)

def makeAppointment(request, id):
    doc = get_object_or_404(DoctorProfile, user=id)

    if request.method == 'POST':
        if request.user.is_anonymous:
            form = AppointmentFormAnonymous(request.POST)
        else:
            form = AppointmentFormLogged(request.POST)
            form.instance.first_name = request.user.first_name
            form.instance.last_name = request.user.last_name
            form.instance.phone_number = request.user.phone_number
        if form.is_valid():
            if not request.user.is_anonymous:
                form.instance.patient = request.user
            form.instance.doctor = doc.user
            form.save()
            messages.success(request, "Pomyślnie umówiono wizytę!") 
            return redirect("main:docProfile", id=id)
        else:
            messages.error(request, "Wypełnij poprawnie formularz, by umówić się na wizytę")
    else:
        if request.user.is_anonymous:
            form = AppointmentFormAnonymous()
        else:
            form = AppointmentFormLogged()
    context = {'doc': doc, 'form': form}
    return render(request, 'docProfile/appointment.html', context)
    

@login_required
def profileView(request):
    today = datetime.now()
    dateNow = today.strftime("%Y-%m-%d")
    timeNow = today.strftime("%H:%M:%S")
    visits_old = Appointment.objects.filter(patient=request.user, date__lt = dateNow)
    visits_today_old = Appointment.objects.filter(patient=request.user, date = dateNow, hour__lt = timeNow)
    visits_today_next = Appointment.objects.filter(patient=request.user, date = dateNow, hour__gte = timeNow)
    visits_next = Appointment.objects.filter(patient=request.user, date__gt = dateNow)

    if request.user.isDoctor:
        doc = request.user
        patients_today = Appointment.objects.filter(doctor=doc, date = dateNow, hour__gte = timeNow)
        patients_future = Appointment.objects.filter(doctor=doc, date__gt = dateNow)
    else:
        patients_today = ""
        patients_future = ""




    context = {'visits_old':visits_old, 'visits_next':visits_next, 'today_old': visits_today_old, 'today_next': visits_today_next, 'patients_today':patients_today, 'patients_future':patients_future}
    return render(request, 'account/userProfile.html', context)

@login_required
def editProfile(request):
    if request.method == 'POST':
        form = UserEditForm(instance=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Pomyślnie edytowano profil użytkownika.")
    else:
        form = UserEditForm(instance=request.user)
    context = {'form':form}
    return render(request, 'account/editProfile.html', context)

@login_required
def editDocProfile(request):
    doc = get_object_or_404(DoctorProfile, user=request.user)
    if request.method == 'POST':
        form = DoctorProfileForm(instance=doc, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Pomyślnie edytowano profil doktora.")
    else:
        form = DoctorProfileForm(instance=doc)
    context = {'form':form, 'doc':doc}

main/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lalezar&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Signika+Negative:wght@600;700&display=swap" rel="stylesheet"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <script src="{% static 'main/js/popup.js' %}"></script>
    {% block css-links %} {% endblock %}
    {% block js-links %} {% endblock %}
    <title>{% block title %} {% endblock %}</title>
</head>

<body>
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <center>
        <li class="{{ message.tags }}">{{ message }}</li>
      </center>
      {% endfor %}
    </ul>
  {% endif %}
    <main>
        <div id="overlay"></div>
        <div id="popup">
            <button onclick="exit()" class="popup-close">&times;</button>
            <div class="logo">
                <span class="logo-main">E-Lekarz.pl</span>
            </div>
            <div class="popup-content">
            </div>
        </div>
        <section class="top">
        <div class="logo">
            <span class="logo-main">E-Lekarz.pl</span>
            <br>
            <span class="logo-alt">Dbaj o zdrowie, to proste!</span>
        </div>
        <div class="nav-links">
            <a class = "nav-links-a" href="{% url 'main:home' %}">Strona Główna</a>
            <a class = "nav-links-b" href="{% url 'main:search' %}">Lista lekarzy</a>
        </div>
        
        <!-- add some if statement here, depending on the user's login status display either this, or their picture and name -->
        {% if not request.user.is_authenticated %}
        <div class="nav-buttons">
                <form action="{% url 'main:login' %}">
                <button type="submit" class="login"><span class="button-content">ZALOGUJ</span></button>
                </form>
                <button onclick="signup()" class="signup"><span class="button-content">ZAREJESTRUJ</span></button>
        </div>
        {% else %}
        <div class="nav-buttons">
            <a href="{% url 'main:profileView' %}" style="color:black">{{ request.user.first_name }}</a>
            <div class="img-user"></div>
        </div>
        {% endif %}
        {% block top-content %} {% endblock %}
        </section>

        {% block content %} {% endblock %}

        <div id="login-content">
            <form>
            <table>
                <tr>
                    <td>E-mail</td>
                    <td><input type="text"></td>
                </tr>
                <tr>
                    <td>Haslo</td>
                    <td><input type="text"></td>
                </tr>
                <tr>
                    <td></td>
                    <td><button>ZALOGUJ</button></td>
                </tr>
            </table>
            </form>
        </div>
        
        <div id="register-content">
            <span>
            Zanim się zarejestrujesz,<br>
            powiedz nam kim jesteś:<br>
            </span>
            <form action="{% url 'main:new' mode='user' %}">
                <button style="margin-top: 40px" >PACJENTEM</button>
            </form>
            <br>
            <form action="{% url 'main:new' mode='doctor' %}">
                <button style="margin-top: 20px">LEKARZEM</button>
            </form>
        </div>
    </main>
</body>

</html>

main/templates/search.html
  {% extends 'base.html' %}
{% load static %}
{% block css-links %}
    <link rel="stylesheet" href="{% static 'main/css/search.css' %}">
{% endblock %}

{% block title %} Lista lekarzy {% endblock %}


{% block top-content %}

{% endblock %}

{%block content%}

<h2> </h2>
<div class="doc-container">
{% for doc in docList.qs %}
<div class="doc-main"> 
	<div class="doc-img"></div>
	<div class="doc-info">
		<h2> {{doc.user.first_name}} {{doc.user.last_name}}</h2>
		<h3> {{doc.get_spec1_display}}{%if doc.spec2%}, {{doc.get_spec2_display}} {%endif%} </h3>
		<h4> {{doc.city}} </h4>
		<h4 style="text-overflow: ellipsis; overflow-inline: clip;"> {{doc.description}} </h3>
	</div>
	<div class="doc-links">
		<form action="{% url 'main:appointment' doc.user.id%}"> 
			<button type="submit">UMÓW WIZYTĘ</button>
		</form>
		<form action="{{ doc.get_absolute_url }}">
			<button type="submit">WIĘCEJ</button>
		</form>
	</div>
</div>
{% empty %}
<h1> Nie znaleziono wyników </h1>
<p> Niestety, ale nie znaleziono lekarzy, którzy spełniają podane kryteria wyszukiwania. </p>
{% endfor %}

</div>

{% endblock %}